import axios from "axios";

// Generated by Google Developers Console
const KEY = "AIzaSyAsPMOFT9pjmWex6GkdZuMYZXVYjaR9QQA";

export default axios.create({
  baseURL: "https://www.googleapis.com/youtube/v3",
  params: {
    part: "snippet",
    type: "video", // Avoid fetching playlists
    maxResults: 5,
    key: KEY,
  },
});
